services:

  - type: web
    name: backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: Data Source=app.db
      - key: Jwt__Key
        value: EstaEsUnaClaveSuperSecreta12345678901234
      - key: Jwt__Issuer
        value: backend
      - key: Jwt__Audience
        value: backendUsers
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:8080
      - key: DOTNET_RUNNING_IN_CONTAINER
        value: "true"
      - key: DOTNET_SYSTEM_GLOBALIZATION_INVARIANT
        value: "true"

  - type: web
    name: frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: frontend/dist
    autoDeploy: true
    envVars:
      - key: VITE_API_URL
        value: https://examen-2025-ii-pds-u1-ricardo-de-la-cruz.onrender.com