name: Infraestructura IaC

on:
  push:
    branches: [ "main" ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Init
        run: terraform init

      - name: Plan
        run: terraform plan

      - name: Apply (auto-approve)
        run: terraform apply -auto-approve
